### ISSUE TITLE
Hyperspetral image widget, IMAGE_TOO_BIG

### ISSUE THREAD

**Issue by take5v** [markotoplak/orange-spectroscopy#114]
If there any specific reason to have constraints on max spacial dimensions:
IMAGE_TOO_BIG = 1024*1024

On my mind, It would be better to warn "Image is too large, press load if you want to proceed" but still have the possibility to load the huge image.

Best regards

**Comment by markotoplak** [comment]
No special reasons, it could be larger, it is just a safeguard from strangely chosen inputs.

What kind of images are you working with? 

I like your suggestion though. Thanks!

**Comment by take5v** [comment]
Thanks, I'm working with FTIR hyperspectral images. Spatial dimensions could be 3k by 2k or so.

**Comment by markotoplak** [comment]
Fixed in 580aea3e
