### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by take5v** [markotoplak/orange-spectroscopy#119]
I found out that loading a hyperspectral image by orange consumes 4 times more memory than by storing it in a plain numpy object. Also, hyperspectral widget doubles the memory consumption. Just curious, was it architecture decision to do so and should it be optimized?

**Comment by markotoplak** [comment]
An Orange data Table currently stores 64-bit bit floats. This might be the first difference.

There is some other info used for the domain but additional part is, at least for images, really tiny. There is quite some data copying, which could be optimized, done in some widgets. For example Curves copies the data and sorts it by increasing wavelenghts (and Hyper uses Curves as a subcomponent).

Some of these could and should be optimized, but doing everything in exactly 1x memory could be harder to maintain and slower to run. But 2x the numpy array should be doable if we remove the inefficiencies.

**Comment by take5v** [comment]
Greetings and a Merry Christmas from my supervisor Achim!

**Comment by markotoplak** [comment]
Thanks for reporting the problem. 2x increase of memory when you connect Spectra or Hyperspectra happens because Orange needlessly copies the whole data when it is producing one of the outputs. Definitely a problem we have to fix.

**Comment by markotoplak** [comment]
A possible solution for needless data copy: biolab/orange3#2911

**Comment by markotoplak** [comment]
Needless copying data tables shouldn't be an issue anymore. But yes, float64 is still used.
