### ISSUE TITLE
OWPreprocess and preprocess.py

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-spectroscopy#131]
Should we redesign the preprocessors? The problem I think is that the (1) GUI doesn't know anything about the data and (2) the data dependent on-the-fly interaction is quite awkward with the GUI. 

Examples: 
(1) In the cut preprocessor, the left and right limits are initialized with hard 0 and 4000 numbers. This kind of makes sense for FTIR (although even there it is a limiting factor), but now that we call the package "spectroscopy" we should expect wildly varying datasets both in the x and y directions.
(2) In some cases, the preprocessor layout should be changing dynamically, like the Normalize preprocessor. Could we make this interaction easier?

I am not sure if we need a whole redesign or just write some connecting functions for both type problems.

**Comment by stuart-cls** [comment]
Happy New Year, Feri! Looks like you had a busy vacation :)

For comment (1), this is not the case. If you look at line 466 of `owpreprocess.py` you can see the limits are automatically set to the min() and max() of the x preview data:

    def set_preview_data(self, data):
        if not self.user_changed:
            x = getx(data)
            if len(x):
                self.set_lowlim(min(x))
                self.set_highlim(max(x))
                self.edited.emit()

For comment (2), I don't understand your idea. Perhaps this could be re-described as a separate, smaller issue?
